# Generated by Django 4.0.3 on 2022-05-27 03:21

from django.db import migrations, models
import file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='dersAdi')),
                ('description', models.TextField(verbose_name='bolum')),
                ('filepath', models.FileField(null=True, upload_to='files/', verbose_name='')),
                ('pdf', models.FileField(upload_to='store/pdfs/')),
                ('publishing_date', models.DateTimeField(verbose_name='Yayınlanma_Tarih')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='dersAdi')),
                ('description', models.TextField(verbose_name='bolum')),
                ('filepath', models.FileField(null=True, upload_to='files/', verbose_name='')),
                ('pdf', models.FileField(upload_to='store/pdfs/')),
                ('publishing_date', models.DateTimeField(verbose_name='Yayınlanma_Tarih')),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=file.models.user_directory_path)),
            ],
        ),
    ]
